### ISSUE TITLE
Dead links - Feb 2024

### ISSUE THREAD

**Issue by horusrogue** [mb224/NerfGecko#2]
M3 BOLTS 
This posting will have all the screw sizes except the 25mm as of 21/03/2021 // https://www.aliexpress.com/item/32773255624.html
A posting for the 25mm, reasonable shipping fees // https://www.aliexpress.com/item/4001334225286.html - 

BRASS INSERTS 
100 PC // https://www.aliexpress.com/item/4001185849382.html

SPRINGS
Some options for the catch spring // https://www.aliexpress.com/item/33052942305.html

**Comment by mb224** [comment]
Fixed! Haven't maintained this in a long time.
